version: "3.6"

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma123
      POSTGRES_DB: prisma
